<script setup>
const updatedAt = '14 de agosto de 2026'

const sections = [
  { title: '1. Alcance', content: 'Estos términos regulan el uso del sitio web y las compras realizadas en Strawberry Makeup. Al navegar, registrarse o realizar un pedido, la persona usuaria acepta estas condiciones.' },
  { title: '2. Productos y disponibilidad', content: 'Las imágenes, tonos y descripciones se presentan como referencia. Puede haber variaciones razonables por iluminación o pantalla. La disponibilidad se confirma al procesar el pedido; si un producto no está disponible, informaremos alternativas o la devolución del valor recibido cuando corresponda.' },
  { title: '3. Precios y pedidos', content: 'Los precios se muestran en pesos colombianos (COP). Antes de confirmar el pedido se informarán el valor de los productos, los costos de envío aplicables y el total. Nos reservamos el derecho de corregir errores manifiestos de precio o información, comunicándolo antes de despachar el pedido.' },
  { title: '4. Envíos y entrega', content: 'Los tiempos y costos de entrega se comunicarán durante la compra según la ubicación y el método de envío. La persona compradora debe suministrar datos de contacto y dirección completos. En caso de novedad en la entrega, podremos comunicarnos por los canales proporcionados.' },
  { title: '5. Cambios, retracto y garantía', content: 'Las solicitudes de cambio, retracto, garantía o reclamación se atenderán de acuerdo con la normativa colombiana aplicable y las condiciones particulares del producto. Para evaluar una solicitud, conserva la factura o comprobante y contáctanos con la información del pedido. Cuando aplique el derecho de retracto, se seguirá el procedimiento y los plazos legales.' },
  { title: '6. Tratamiento de datos personales', content: 'Usamos los datos que suministras para gestionar pedidos, entregas, pagos, atención al cliente y, cuando exista autorización, comunicaciones comerciales. Puedes solicitar conocer, actualizar, corregir o suprimir tus datos mediante el correo strawberrymakeupstore@gmail.com. Trataremos la información conforme a la Ley 1581 de 2012 y la normativa aplicable.' },
  { title: '7. Uso del sitio', content: 'No está permitido usar el sitio para fines ilícitos, afectar su seguridad, intentar acceder a información no autorizada o usar contenidos de la marca sin autorización. Los nombres, diseños, fotografías y demás contenidos del sitio están protegidos por la legislación aplicable.' },
  { title: '8. Atención de solicitudes', content: 'Para peticiones, quejas, reclamos o solicitudes relacionadas con un pedido, escríbenos a strawberrymakeupstore@gmail.com o comunícate al +57 323 527 5634. Procuraremos responder dentro de los términos legales aplicables.' },
  { title: '9. Actualizaciones', content: 'Podemos actualizar estos términos para reflejar cambios operativos o normativos. La versión vigente estará publicada en esta página e indicará su fecha de actualización.' }
]
</script>

<template>
  <main class="bg-pink-50/40 py-12 sm:py-18"><article class="mx-auto max-w-4xl rounded-3xl bg-white px-6 py-10 shadow-sm sm:px-12 sm:py-14"><p class="text-sm font-bold tracking-[0.2em] text-[var(--primary)]">INFORMACIÓN LEGAL</p><h1 class="mt-3 text-4xl font-bold text-black sm:text-5xl">Términos y condiciones</h1><p class="mt-4 text-sm text-neutral-500">Última actualización: {{ updatedAt }}</p><p class="mt-8 rounded-xl border-l-4 border-[var(--primary)] bg-pink-50 p-5 leading-7 text-neutral-700">Este documento es una guía inicial para Strawberry Makeup y debe ser revisado por una persona profesional en derecho antes de su publicación definitiva.</p><div class="mt-10 space-y-9"><section v-for="section in sections" :key="section.title"><h2 class="text-xl font-bold text-[var(--primary)]">{{ section.title }}</h2><p class="mt-3 leading-7 text-neutral-700">{{ section.content }}</p></section></div><div class="mt-12 rounded-2xl bg-black p-6 text-white"><h2 class="text-xl font-bold">¿Tienes preguntas?</h2><p class="mt-2 text-white/75">Escríbenos a strawberrymakeupstore@gmail.com.</p></div></article></main>
</template>
